// Code generated by protoc-gen-go.
// source: pingpong.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	pingpong.proto

It has these top-level messages:
	IdMessage
	ConnectRequest
	DisconnectReply
	Notification
	ConnectReply
	GameEvent
	GameStatus
	PlayRequest
	PlayReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

// ---- Identification message
type IdMessage struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *IdMessage) Reset()                    { *m = IdMessage{} }
func (m *IdMessage) String() string            { return proto1.CompactTextString(m) }
func (*IdMessage) ProtoMessage()               {}
func (*IdMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// ---- Connect
type ConnectRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ConnectRequest) Reset()                    { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string            { return proto1.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()               {}
func (*ConnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// ---- Disconnect
type DisconnectReply struct {
}

func (m *DisconnectReply) Reset()                    { *m = DisconnectReply{} }
func (m *DisconnectReply) String() string            { return proto1.CompactTextString(m) }
func (*DisconnectReply) ProtoMessage()               {}
func (*DisconnectReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// ---- Notification
type Notification struct {
	// Types that are valid to be assigned to Body:
	//	*Notification_ConnectReply
	//	*Notification_GameEvent
	//	*Notification_GameStatus
	Body isNotification_Body `protobuf_oneof:"body"`
}

func (m *Notification) Reset()                    { *m = Notification{} }
func (m *Notification) String() string            { return proto1.CompactTextString(m) }
func (*Notification) ProtoMessage()               {}
func (*Notification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isNotification_Body interface {
	isNotification_Body()
}

type Notification_ConnectReply struct {
	ConnectReply *ConnectReply `protobuf:"bytes,1,opt,name=connect_reply,json=connectReply,oneof"`
}
type Notification_GameEvent struct {
	GameEvent *GameEvent `protobuf:"bytes,2,opt,name=game_event,json=gameEvent,oneof"`
}
type Notification_GameStatus struct {
	GameStatus *GameStatus `protobuf:"bytes,3,opt,name=game_status,json=gameStatus,oneof"`
}

func (*Notification_ConnectReply) isNotification_Body() {}
func (*Notification_GameEvent) isNotification_Body()    {}
func (*Notification_GameStatus) isNotification_Body()   {}

func (m *Notification) GetBody() isNotification_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Notification) GetConnectReply() *ConnectReply {
	if x, ok := m.GetBody().(*Notification_ConnectReply); ok {
		return x.ConnectReply
	}
	return nil
}

func (m *Notification) GetGameEvent() *GameEvent {
	if x, ok := m.GetBody().(*Notification_GameEvent); ok {
		return x.GameEvent
	}
	return nil
}

func (m *Notification) GetGameStatus() *GameStatus {
	if x, ok := m.GetBody().(*Notification_GameStatus); ok {
		return x.GameStatus
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Notification) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _Notification_OneofMarshaler, _Notification_OneofUnmarshaler, _Notification_OneofSizer, []interface{}{
		(*Notification_ConnectReply)(nil),
		(*Notification_GameEvent)(nil),
		(*Notification_GameStatus)(nil),
	}
}

func _Notification_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*Notification)
	// body
	switch x := m.Body.(type) {
	case *Notification_ConnectReply:
		b.EncodeVarint(1<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.ConnectReply); err != nil {
			return err
		}
	case *Notification_GameEvent:
		b.EncodeVarint(2<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.GameEvent); err != nil {
			return err
		}
	case *Notification_GameStatus:
		b.EncodeVarint(3<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.GameStatus); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Notification.Body has unexpected type %T", x)
	}
	return nil
}

func _Notification_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*Notification)
	switch tag {
	case 1: // body.connect_reply
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(ConnectReply)
		err := b.DecodeMessage(msg)
		m.Body = &Notification_ConnectReply{msg}
		return true, err
	case 2: // body.game_event
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(GameEvent)
		err := b.DecodeMessage(msg)
		m.Body = &Notification_GameEvent{msg}
		return true, err
	case 3: // body.game_status
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(GameStatus)
		err := b.DecodeMessage(msg)
		m.Body = &Notification_GameStatus{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Notification_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*Notification)
	// body
	switch x := m.Body.(type) {
	case *Notification_ConnectReply:
		s := proto1.Size(x.ConnectReply)
		n += proto1.SizeVarint(1<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *Notification_GameEvent:
		s := proto1.Size(x.GameEvent)
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *Notification_GameStatus:
		s := proto1.Size(x.GameStatus)
		n += proto1.SizeVarint(3<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ConnectReply struct {
	Id    int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Sound int32 `protobuf:"varint,2,opt,name=sound" json:"sound,omitempty"`
}

func (m *ConnectReply) Reset()                    { *m = ConnectReply{} }
func (m *ConnectReply) String() string            { return proto1.CompactTextString(m) }
func (*ConnectReply) ProtoMessage()               {}
func (*ConnectReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GameEvent struct {
	Sound     int32                      `protobuf:"varint,1,opt,name=sound" json:"sound,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *GameEvent) Reset()                    { *m = GameEvent{} }
func (m *GameEvent) String() string            { return proto1.CompactTextString(m) }
func (*GameEvent) ProtoMessage()               {}
func (*GameEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GameEvent) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type GameStatus struct {
	// The history of the conversation
	Pingpong []*GameEvent `protobuf:"bytes,1,rep,name=pingpong" json:"pingpong,omitempty"`
	// The sound of the player that is allowed to talk now
	CurrentSound int32 `protobuf:"varint,2,opt,name=currentSound" json:"currentSound,omitempty"`
}

func (m *GameStatus) Reset()                    { *m = GameStatus{} }
func (m *GameStatus) String() string            { return proto1.CompactTextString(m) }
func (*GameStatus) ProtoMessage()               {}
func (*GameStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GameStatus) GetPingpong() []*GameEvent {
	if m != nil {
		return m.Pingpong
	}
	return nil
}

// ---- Play
type PlayRequest struct {
	// Id of the player
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *PlayRequest) Reset()                    { *m = PlayRequest{} }
func (m *PlayRequest) String() string            { return proto1.CompactTextString(m) }
func (*PlayRequest) ProtoMessage()               {}
func (*PlayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type PlayReply struct {
	// Acceptation status - was it the player's turn to play?
	Accepted bool `protobuf:"varint,1,opt,name=accepted" json:"accepted,omitempty"`
}

func (m *PlayReply) Reset()                    { *m = PlayReply{} }
func (m *PlayReply) String() string            { return proto1.CompactTextString(m) }
func (*PlayReply) ProtoMessage()               {}
func (*PlayReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto1.RegisterType((*IdMessage)(nil), "pingpong.IdMessage")
	proto1.RegisterType((*ConnectRequest)(nil), "pingpong.ConnectRequest")
	proto1.RegisterType((*DisconnectReply)(nil), "pingpong.DisconnectReply")
	proto1.RegisterType((*Notification)(nil), "pingpong.Notification")
	proto1.RegisterType((*ConnectReply)(nil), "pingpong.ConnectReply")
	proto1.RegisterType((*GameEvent)(nil), "pingpong.GameEvent")
	proto1.RegisterType((*GameStatus)(nil), "pingpong.GameStatus")
	proto1.RegisterType((*PlayRequest)(nil), "pingpong.PlayRequest")
	proto1.RegisterType((*PlayReply)(nil), "pingpong.PlayReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for PingPong service

type PingPongClient interface {
	// Connects to the server to get an id to use in other messages
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (PingPong_ConnectClient, error)
	// Disconnect from the server
	Disconnect(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*DisconnectReply, error)
	// Request a notification from the server
	GetGameStatus(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*GameStatus, error)
	// Let the server know the client's move for the game
	Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlayReply, error)
}

type pingPongClient struct {
	cc *grpc.ClientConn
}

func NewPingPongClient(cc *grpc.ClientConn) PingPongClient {
	return &pingPongClient{cc}
}

func (c *pingPongClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (PingPong_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PingPong_serviceDesc.Streams[0], c.cc, "/pingpong.PingPong/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingPongConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PingPong_ConnectClient interface {
	Recv() (*Notification, error)
	grpc.ClientStream
}

type pingPongConnectClient struct {
	grpc.ClientStream
}

func (x *pingPongConnectClient) Recv() (*Notification, error) {
	m := new(Notification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pingPongClient) Disconnect(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*DisconnectReply, error) {
	out := new(DisconnectReply)
	err := grpc.Invoke(ctx, "/pingpong.PingPong/Disconnect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingPongClient) GetGameStatus(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*GameStatus, error) {
	out := new(GameStatus)
	err := grpc.Invoke(ctx, "/pingpong.PingPong/GetGameStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingPongClient) Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlayReply, error) {
	out := new(PlayReply)
	err := grpc.Invoke(ctx, "/pingpong.PingPong/Play", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PingPong service

type PingPongServer interface {
	// Connects to the server to get an id to use in other messages
	Connect(*ConnectRequest, PingPong_ConnectServer) error
	// Disconnect from the server
	Disconnect(context.Context, *IdMessage) (*DisconnectReply, error)
	// Request a notification from the server
	GetGameStatus(context.Context, *IdMessage) (*GameStatus, error)
	// Let the server know the client's move for the game
	Play(context.Context, *PlayRequest) (*PlayReply, error)
}

func RegisterPingPongServer(s *grpc.Server, srv PingPongServer) {
	s.RegisterService(&_PingPong_serviceDesc, srv)
}

func _PingPong_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingPongServer).Connect(m, &pingPongConnectServer{stream})
}

type PingPong_ConnectServer interface {
	Send(*Notification) error
	grpc.ServerStream
}

type pingPongConnectServer struct {
	grpc.ServerStream
}

func (x *pingPongConnectServer) Send(m *Notification) error {
	return x.ServerStream.SendMsg(m)
}

func _PingPong_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.PingPong/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).Disconnect(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingPong_GetGameStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).GetGameStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.PingPong/GetGameStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).GetGameStatus(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingPong_Play_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).Play(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.PingPong/Play",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).Play(ctx, req.(*PlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingPong_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pingpong.PingPong",
	HandlerType: (*PingPongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Disconnect",
			Handler:    _PingPong_Disconnect_Handler,
		},
		{
			MethodName: "GetGameStatus",
			Handler:    _PingPong_GetGameStatus_Handler,
		},
		{
			MethodName: "Play",
			Handler:    _PingPong_Play_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _PingPong_Connect_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xdb, 0xb8, 0xb5, 0x27, 0x6e, 0x10, 0xd3, 0x82, 0x8c, 0x11, 0x02, 0xad, 0x90, 0xe0,
	0xe4, 0xa0, 0x12, 0x09, 0x0e, 0x7c, 0x48, 0x2d, 0xa8, 0x70, 0x00, 0x45, 0x5b, 0x4e, 0x70, 0xa8,
	0x5c, 0x7b, 0x63, 0x59, 0x4a, 0x76, 0x8d, 0xbd, 0x46, 0xca, 0xff, 0xe3, 0x7f, 0xc1, 0x7a, 0x1d,
	0xdb, 0x1b, 0x2b, 0x3d, 0xd9, 0x33, 0xf3, 0xde, 0xce, 0xc7, 0x7b, 0x30, 0xcd, 0x33, 0x9e, 0xe6,
	0x82, 0xa7, 0x61, 0x5e, 0x08, 0x29, 0xd0, 0x69, 0xe3, 0xe0, 0x69, 0x2a, 0x44, 0xba, 0x62, 0x33,
	0x9d, 0xbf, 0xad, 0x96, 0x33, 0x99, 0xad, 0x59, 0x29, 0xa3, 0x75, 0xde, 0x40, 0xc9, 0x63, 0x70,
	0xbf, 0x26, 0xdf, 0x58, 0x59, 0x46, 0x29, 0xc3, 0x29, 0x1c, 0x64, 0x89, 0x6f, 0x3d, 0xb3, 0x5e,
	0xda, 0x54, 0xfd, 0x91, 0xe7, 0x30, 0xbd, 0x14, 0x9c, 0xb3, 0x58, 0x52, 0xf6, 0xbb, 0x52, 0x3c,
	0x44, 0x18, 0xf3, 0x68, 0xcd, 0x34, 0xc6, 0xa5, 0xfa, 0x9f, 0xdc, 0x87, 0x7b, 0x9f, 0xb2, 0x32,
	0x6e, 0x81, 0xf9, 0x6a, 0x43, 0xfe, 0x5a, 0xe0, 0x7d, 0x17, 0x32, 0x5b, 0x66, 0x71, 0x24, 0x33,
	0xc1, 0xf1, 0x3d, 0x9c, 0x6c, 0x01, 0x37, 0x45, 0x8d, 0xd0, 0x0f, 0x4c, 0xce, 0x1f, 0x86, 0xdd,
	0xe4, 0x97, 0x06, 0xff, 0xcb, 0x88, 0x7a, 0xe6, 0x7b, 0x38, 0x07, 0x48, 0x55, 0xab, 0x1b, 0xf6,
	0x87, 0x71, 0xe9, 0x1f, 0x68, 0xee, 0x69, 0xcf, 0xbd, 0x52, 0xb5, 0xcf, 0x75, 0x49, 0x11, 0xdd,
	0xb4, 0x0d, 0xf0, 0x0d, 0x4c, 0x34, 0x4b, 0xed, 0x2b, 0xab, 0xd2, 0x3f, 0xd4, 0xb4, 0xb3, 0x5d,
	0xda, 0xb5, 0xae, 0x29, 0x9e, 0x6e, 0xd0, 0x44, 0x17, 0x47, 0x30, 0xbe, 0x15, 0xc9, 0x86, 0xcc,
	0xc1, 0x33, 0xc7, 0x1a, 0xde, 0x07, 0xcf, 0xc0, 0x2e, 0x45, 0xc5, 0x13, 0x3d, 0x91, 0x4d, 0x9b,
	0x80, 0xfc, 0x02, 0xb7, 0x1b, 0xa8, 0x87, 0x58, 0x06, 0x04, 0xdf, 0x82, 0xdb, 0x09, 0xb1, 0x5d,
	0x27, 0x08, 0x1b, 0xa9, 0xc2, 0x56, 0xaa, 0xf0, 0x47, 0x8b, 0xa0, 0x3d, 0x98, 0x44, 0x00, 0xfd,
	0xd8, 0x38, 0x83, 0x4e, 0x6a, 0xd5, 0xe0, 0xf0, 0x8e, 0xab, 0xd0, 0x0e, 0x84, 0x04, 0xbc, 0xb8,
	0x2a, 0x0a, 0x95, 0xbc, 0x36, 0x06, 0xdf, 0xc9, 0x91, 0x27, 0x30, 0x59, 0xac, 0xa2, 0x4d, 0x2b,
	0xf9, 0xd0, 0x14, 0x2f, 0xc0, 0x6d, 0xca, 0xf5, 0x45, 0x02, 0x70, 0xa2, 0x38, 0x66, 0xb9, 0x64,
	0x0d, 0xc4, 0xa1, 0x5d, 0x7c, 0xfe, 0xcf, 0x02, 0x67, 0xa1, 0x1a, 0x2f, 0xea, 0xc6, 0x1f, 0xe1,
	0x78, 0x7b, 0x4a, 0xf4, 0xf7, 0x88, 0xae, 0x5b, 0x05, 0x86, 0x1d, 0x4c, 0xf7, 0x90, 0xd1, 0x2b,
	0x0b, 0x3f, 0x00, 0xf4, 0x2e, 0x43, 0x63, 0xcd, 0xce, 0xbe, 0xc1, 0xa3, 0x3e, 0x39, 0x34, 0xe4,
	0x08, 0xdf, 0xc1, 0xc9, 0x15, 0x93, 0xc6, 0xed, 0xf6, 0x3e, 0xb1, 0xd7, 0x1d, 0x8a, 0x3d, 0x87,
	0x71, 0xbd, 0x34, 0x3e, 0xe8, 0xeb, 0xc6, 0x8d, 0x82, 0xd3, 0x61, 0x5a, 0xf7, 0xbc, 0x38, 0xfe,
	0x69, 0x37, 0x6a, 0x1e, 0xe9, 0xcf, 0xeb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x43, 0xb0, 0xe6,
	0x98, 0xa9, 0x03, 0x00, 0x00,
}
