// Code generated by protoc-gen-go.
// source: pingpong.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	pingpong.proto

It has these top-level messages:
	IdMessage
	ConnectRequest
	ConnectReply
	Notification
	GameEvent
	GameStatus
	PlayRequest
	PlayReply
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// ---- Identification message
type IdMessage struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *IdMessage) Reset()                    { *m = IdMessage{} }
func (m *IdMessage) String() string            { return proto.CompactTextString(m) }
func (*IdMessage) ProtoMessage()               {}
func (*IdMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// ---- Connect
type ConnectRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ConnectRequest) Reset()                    { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()               {}
func (*ConnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ConnectReply struct {
	// Id of the player
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ConnectReply) Reset()                    { *m = ConnectReply{} }
func (m *ConnectReply) String() string            { return proto.CompactTextString(m) }
func (*ConnectReply) ProtoMessage()               {}
func (*ConnectReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// ---- Notification
type Notification struct {
	// Types that are valid to be assigned to Event:
	//	*Notification_Id
	//	*Notification_GameEvent
	//	*Notification_GameStatus
	Event isNotification_Event `protobuf_oneof:"event"`
}

func (m *Notification) Reset()                    { *m = Notification{} }
func (m *Notification) String() string            { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()               {}
func (*Notification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isNotification_Event interface {
	isNotification_Event()
}

type Notification_Id struct {
	Id *IdMessage `protobuf:"bytes,1,opt,name=id,oneof"`
}
type Notification_GameEvent struct {
	GameEvent *GameEvent `protobuf:"bytes,2,opt,name=game_event,json=gameEvent,oneof"`
}
type Notification_GameStatus struct {
	GameStatus *GameStatus `protobuf:"bytes,3,opt,name=game_status,json=gameStatus,oneof"`
}

func (*Notification_Id) isNotification_Event()         {}
func (*Notification_GameEvent) isNotification_Event()  {}
func (*Notification_GameStatus) isNotification_Event() {}

func (m *Notification) GetEvent() isNotification_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Notification) GetId() *IdMessage {
	if x, ok := m.GetEvent().(*Notification_Id); ok {
		return x.Id
	}
	return nil
}

func (m *Notification) GetGameEvent() *GameEvent {
	if x, ok := m.GetEvent().(*Notification_GameEvent); ok {
		return x.GameEvent
	}
	return nil
}

func (m *Notification) GetGameStatus() *GameStatus {
	if x, ok := m.GetEvent().(*Notification_GameStatus); ok {
		return x.GameStatus
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Notification) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Notification_OneofMarshaler, _Notification_OneofUnmarshaler, _Notification_OneofSizer, []interface{}{
		(*Notification_Id)(nil),
		(*Notification_GameEvent)(nil),
		(*Notification_GameStatus)(nil),
	}
}

func _Notification_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Notification)
	// event
	switch x := m.Event.(type) {
	case *Notification_Id:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Id); err != nil {
			return err
		}
	case *Notification_GameEvent:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GameEvent); err != nil {
			return err
		}
	case *Notification_GameStatus:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GameStatus); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Notification.Event has unexpected type %T", x)
	}
	return nil
}

func _Notification_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Notification)
	switch tag {
	case 1: // event.id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IdMessage)
		err := b.DecodeMessage(msg)
		m.Event = &Notification_Id{msg}
		return true, err
	case 2: // event.game_event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GameEvent)
		err := b.DecodeMessage(msg)
		m.Event = &Notification_GameEvent{msg}
		return true, err
	case 3: // event.game_status
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GameStatus)
		err := b.DecodeMessage(msg)
		m.Event = &Notification_GameStatus{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Notification_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Notification)
	// event
	switch x := m.Event.(type) {
	case *Notification_Id:
		s := proto.Size(x.Id)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Notification_GameEvent:
		s := proto.Size(x.GameEvent)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Notification_GameStatus:
		s := proto.Size(x.GameStatus)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GameEvent struct {
	PlayerId  int32                      `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *GameEvent) Reset()                    { *m = GameEvent{} }
func (m *GameEvent) String() string            { return proto.CompactTextString(m) }
func (*GameEvent) ProtoMessage()               {}
func (*GameEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GameEvent) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type GameStatus struct {
	// The history of the conversation
	Pingpong []*GameEvent `protobuf:"bytes,1,rep,name=pingpong" json:"pingpong,omitempty"`
	// The id of the player that is allowed to talk now
	CurrentPlayer int32 `protobuf:"varint,2,opt,name=currentPlayer" json:"currentPlayer,omitempty"`
}

func (m *GameStatus) Reset()                    { *m = GameStatus{} }
func (m *GameStatus) String() string            { return proto.CompactTextString(m) }
func (*GameStatus) ProtoMessage()               {}
func (*GameStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GameStatus) GetPingpong() []*GameEvent {
	if m != nil {
		return m.Pingpong
	}
	return nil
}

// ---- Play
type PlayRequest struct {
	// Id of the player
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *PlayRequest) Reset()                    { *m = PlayRequest{} }
func (m *PlayRequest) String() string            { return proto.CompactTextString(m) }
func (*PlayRequest) ProtoMessage()               {}
func (*PlayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type PlayReply struct {
	// Acceptation status - was it the player's turn to play?
	Accepted bool `protobuf:"varint,1,opt,name=accepted" json:"accepted,omitempty"`
}

func (m *PlayReply) Reset()                    { *m = PlayReply{} }
func (m *PlayReply) String() string            { return proto.CompactTextString(m) }
func (*PlayReply) ProtoMessage()               {}
func (*PlayReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*IdMessage)(nil), "pingpong.IdMessage")
	proto.RegisterType((*ConnectRequest)(nil), "pingpong.ConnectRequest")
	proto.RegisterType((*ConnectReply)(nil), "pingpong.ConnectReply")
	proto.RegisterType((*Notification)(nil), "pingpong.Notification")
	proto.RegisterType((*GameEvent)(nil), "pingpong.GameEvent")
	proto.RegisterType((*GameStatus)(nil), "pingpong.GameStatus")
	proto.RegisterType((*PlayRequest)(nil), "pingpong.PlayRequest")
	proto.RegisterType((*PlayReply)(nil), "pingpong.PlayReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for PingPong service

type PingPongClient interface {
	// Connects to the server to get an id to use in other messages
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (PingPong_ConnectClient, error)
	// Request a notification from the server
	GetGameStatus(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*GameStatus, error)
	// Let the server know the client's move for the game
	Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlayReply, error)
}

type pingPongClient struct {
	cc *grpc.ClientConn
}

func NewPingPongClient(cc *grpc.ClientConn) PingPongClient {
	return &pingPongClient{cc}
}

func (c *pingPongClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (PingPong_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PingPong_serviceDesc.Streams[0], c.cc, "/pingpong.PingPong/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingPongConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PingPong_ConnectClient interface {
	Recv() (*Notification, error)
	grpc.ClientStream
}

type pingPongConnectClient struct {
	grpc.ClientStream
}

func (x *pingPongConnectClient) Recv() (*Notification, error) {
	m := new(Notification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pingPongClient) GetGameStatus(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*GameStatus, error) {
	out := new(GameStatus)
	err := grpc.Invoke(ctx, "/pingpong.PingPong/GetGameStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingPongClient) Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlayReply, error) {
	out := new(PlayReply)
	err := grpc.Invoke(ctx, "/pingpong.PingPong/Play", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PingPong service

type PingPongServer interface {
	// Connects to the server to get an id to use in other messages
	Connect(*ConnectRequest, PingPong_ConnectServer) error
	// Request a notification from the server
	GetGameStatus(context.Context, *IdMessage) (*GameStatus, error)
	// Let the server know the client's move for the game
	Play(context.Context, *PlayRequest) (*PlayReply, error)
}

func RegisterPingPongServer(s *grpc.Server, srv PingPongServer) {
	s.RegisterService(&_PingPong_serviceDesc, srv)
}

func _PingPong_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingPongServer).Connect(m, &pingPongConnectServer{stream})
}

type PingPong_ConnectServer interface {
	Send(*Notification) error
	grpc.ServerStream
}

type pingPongConnectServer struct {
	grpc.ServerStream
}

func (x *pingPongConnectServer) Send(m *Notification) error {
	return x.ServerStream.SendMsg(m)
}

func _PingPong_GetGameStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).GetGameStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.PingPong/GetGameStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).GetGameStatus(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingPong_Play_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).Play(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.PingPong/Play",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).Play(ctx, req.(*PlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingPong_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pingpong.PingPong",
	HandlerType: (*PingPongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameStatus",
			Handler:    _PingPong_GetGameStatus_Handler,
		},
		{
			MethodName: "Play",
			Handler:    _PingPong_Play_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _PingPong_Connect_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x6d, 0xf9, 0x90, 0x76, 0xf8, 0x38, 0x2c, 0x6a, 0x9a, 0x1a, 0x3f, 0xb2, 0xc1, 0xe8, 0xa9,
	0x18, 0x34, 0xd1, 0x83, 0x89, 0x09, 0xc6, 0x20, 0x07, 0x0d, 0xa9, 0x9e, 0xbc, 0x90, 0x52, 0x96,
	0xa6, 0x09, 0x74, 0x6b, 0xbb, 0x35, 0xe1, 0x47, 0xf9, 0x1b, 0xfc, 0x6b, 0x6e, 0xb7, 0x74, 0x0b,
	0x88, 0xa7, 0xdd, 0x99, 0x79, 0xb3, 0xf3, 0xde, 0xbc, 0x85, 0x56, 0xe8, 0x07, 0x5e, 0x48, 0x03,
	0xcf, 0x0a, 0x23, 0xca, 0x28, 0xd2, 0xf2, 0xd8, 0x3c, 0xf5, 0x28, 0xf5, 0xe6, 0xa4, 0x2b, 0xf2,
	0x93, 0x64, 0xd6, 0x65, 0xfe, 0x82, 0xc4, 0xcc, 0x59, 0x84, 0x19, 0x14, 0x1f, 0x81, 0x3e, 0x9c,
	0xbe, 0x90, 0x38, 0x76, 0x3c, 0x82, 0x5a, 0x50, 0xf2, 0xa7, 0x86, 0x7a, 0xa6, 0x5e, 0x56, 0x6d,
	0x7e, 0xc3, 0x1d, 0x68, 0x3d, 0xd2, 0x20, 0x20, 0x2e, 0xb3, 0xc9, 0x67, 0xc2, 0xfb, 0x10, 0x82,
	0x4a, 0xe0, 0x2c, 0x88, 0xc0, 0xe8, 0xb6, 0xb8, 0xe3, 0x13, 0x68, 0x48, 0x54, 0x38, 0x5f, 0xfe,
	0x79, 0xe5, 0x5b, 0x85, 0xc6, 0x2b, 0x65, 0xfe, 0xcc, 0x77, 0x1d, 0xe6, 0xd3, 0x00, 0x9d, 0x4b,
	0x40, 0xbd, 0xd7, 0xb6, 0x24, 0x77, 0xc9, 0xe3, 0x59, 0x49, 0xfb, 0xd0, 0x0d, 0x80, 0xc7, 0xdf,
	0x1f, 0x93, 0x2f, 0x12, 0x30, 0xa3, 0xb4, 0x0d, 0x1f, 0xf0, 0xda, 0x53, 0x5a, 0xe2, 0x70, 0xdd,
	0xcb, 0x03, 0x74, 0x0b, 0x75, 0xd1, 0xc5, 0x45, 0xb2, 0x24, 0x36, 0xca, 0xa2, 0x6d, 0x7f, 0xb3,
	0xed, 0x4d, 0xd4, 0x78, 0x9f, 0x18, 0x90, 0x45, 0xfd, 0x1a, 0x54, 0xc5, 0x24, 0x3c, 0x01, 0x5d,
	0xbe, 0x8d, 0xf8, 0x7e, 0xc2, 0xb9, 0xb3, 0x24, 0xd1, 0x58, 0x6a, 0xd2, 0xb2, 0xc4, 0x70, 0x8a,
	0xee, 0x40, 0x97, 0xfb, 0x5c, 0x11, 0x34, 0xad, 0x6c, 0xe3, 0x56, 0xbe, 0x71, 0xeb, 0x3d, 0x47,
	0xd8, 0x05, 0x18, 0xbb, 0x00, 0x05, 0x11, 0xd4, 0x05, 0xe9, 0x18, 0x9f, 0x51, 0xfe, 0x47, 0xa7,
	0x2d, 0x41, 0xa8, 0x03, 0x4d, 0x37, 0x89, 0x22, 0x9e, 0x1c, 0x09, 0x2e, 0x62, 0x78, 0xd5, 0xde,
	0x4c, 0xe2, 0x63, 0xa8, 0xa7, 0xb7, 0xdc, 0xbb, 0x6d, 0x5f, 0x2e, 0x40, 0xcf, 0xca, 0xa9, 0x69,
	0x26, 0x68, 0x8e, 0xeb, 0x92, 0x90, 0x91, 0x0c, 0xa2, 0xd9, 0x32, 0xee, 0xfd, 0xa8, 0xa0, 0x8d,
	0xf8, 0xe8, 0x51, 0x3a, 0xfa, 0x01, 0x6a, 0x2b, 0xb7, 0x91, 0x51, 0x90, 0xdc, 0xfc, 0x26, 0xe6,
	0x61, 0x51, 0x59, 0x77, 0x1e, 0x2b, 0x57, 0x2a, 0xba, 0x87, 0xe6, 0x80, 0xb0, 0x35, 0xf5, 0xbb,
	0xbe, 0x80, 0xb9, 0xd3, 0x31, 0xac, 0xf0, 0x4f, 0x51, 0x49, 0x49, 0xa3, 0x83, 0xa2, 0xbe, 0xa6,
	0xd1, 0x6c, 0x6f, 0xa7, 0xb9, 0x36, 0xac, 0xf4, 0xb5, 0x8f, 0x3d, 0xe1, 0x47, 0x3c, 0xc9, 0xce,
	0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x40, 0x87, 0x23, 0x33, 0x03, 0x00, 0x00,
}
